# Generated by Django 4.2.17 on 2025-02-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="min_read",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.RemoveField(
            model_name="post",
            name="view_count",
        ),
    ]
