# Generated by Django 4.2.17 on 2025-02-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_min_read_remove_post_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
