# Generated by Django 4.2.17 on 2025-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feeds", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedprefernce",
            name="exclude_topics",
            field=models.ManyToManyField(
                related_name="exclude_by_users", to="topics.topic"
            ),
        ),
        migrations.AddField(
            model_name="userfeedprefernce",
            name="preferred_topics",
            field=models.ManyToManyField(
                related_name="preffered_by_users", to="topics.topic"
            ),
        ),
    ]
