# Generated by Django 4.2.17 on 2025-02-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("feeds", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedprefernce",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_preferences",
                to="users.user",
            ),
        ),
    ]
