# Generated by Django 4.2.17 on 2025-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="topic_icons/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topics",
            },
        ),
    ]
