# Generated by Django 4.2.17 on 2025-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="followers",
            field=models.ManyToManyField(
                related_name="followed_topics", to="users.user"
            ),
        ),
    ]
