# Generated by Django 4.2.17 on 2025-02-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="followers",
        ),
    ]
