# Generated by Django 4.2.17 on 2025-02-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_remove_topic_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="description",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="icon",
        ),
    ]
