# Generated by Django 4.2.17 on 2025-02-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_remove_topic_description_remove_topic_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="slug",
        ),
    ]
